
const LANDMARKS = [
  {
    id: "ESB",
    name: "Empire State Building",
    zone: "Midtown",
    lat: 40.7484,
    lng: -73.9967,
    secret: "ESB_QUANTUM_7X9K_SECRET",
    hint: "Look up — it touches the clouds",
    points: 100,
  },
  {
    id: "BKBR",
    name: "Brooklyn Bridge",
    zone: "Downtown",
    lat: 40.7061,
    lng: -73.9969,
    secret: "BKBR_ENTNGL_4M2R_SECRET",
    hint: "Where two boroughs become one",
    points: 100,
  },
  {
    id: "CENT",
    name: "Central Park Bethesda",
    zone: "Uptown",
    lat: 40.7739,
    lng: -73.9709,
    secret: "CENT_WAVEFN_8Q5T_SECRET",
    hint: "The angel watches over the water",
    points: 100,
  },
  {
    id: "TIME",
    name: "Times Square",
    zone: "Midtown",
    lat: 40.758,
    lng: -73.9855,
    secret: "TSQR_DECOHR_2P7W_SECRET",
    hint: "Where the ball drops",
    points: 75,
  },
  {
    id: "HIGH",
    name: "The High Line",
    zone: "Chelsea",
    lat: 40.748,
    lng: -74.0048,
    secret: "HIGH_SCHRD_6L3V_SECRET",
    hint: "A park above the street",
    points: 125,
  },
  {
    id: "CONY",
    name: "Coney Island",
    zone: "Brooklyn",
    lat: 40.5755,
    lng: -73.9707,
    secret: "CONY_QBIT_9N1S_SECRET",
    hint: "The Wonder Wheel never stops turning",
    points: 150,
  },
  
  {
    id: "FLTN",
    name: "Flatiron Building",
    zone: "Midtown",
    lat: 40.7411,
    lng: -73.9897,
    secret: "FLTN_SUPER_3K7M_SECRET",
    hint: "The ship's prow of Fifth Avenue",
    points: 100,
  },
  {
    id: "911M",
    name: "9/11 Memorial",
    zone: "Downtown",
    lat: 40.7115,
    lng: -74.0134,
    secret: "911M_PHASE_8R2N_SECRET",
    hint: "Reflecting pools of remembrance",
    points: 125,
  },
  {
    id: "ROCK",
    name: "Rockefeller Center",
    zone: "Midtown",
    lat: 40.7587,
    lng: -73.9787,
    secret: "ROCK_FIELD_5T4W_SECRET",
    hint: "Where ice skaters circle in winter",
    points: 100,
  },
  {
    id: "GCTS",
    name: "Grand Central Terminal",
    zone: "Midtown",
    lat: 40.7527,
    lng: -73.9772,
    secret: "GCTS_CLOCK_7P8Q_SECRET",
    hint: "Look up at the ceiling — backwards constellations",
    points: 100,
  },
  {
    id: "NYPL",
    name: "NY Public Library",
    zone: "Midtown",
    lat: 40.7532,
    lng: -73.9822,
    secret: "NYPL_LION_4M6T_SECRET",
    hint: "Between Patience and Fortitude",
    points: 100,
  },
  {
    id: "UNSC",
    name: "United Nations HQ",
    zone: "Midtown",
    lat: 40.7489,
    lng: -73.9680,
    secret: "UNSC_PEACE_9L3K_SECRET",
    hint: "International territory in Manhattan",
    points: 125,
  },
  {
    id: "WLSP",
    name: "Wall Street Bull",
    zone: "Downtown",
    lat: 40.7055,
    lng: -74.0134,
    secret: "WLSP_BULL_2N8R_SECRET",
    hint: "Bronze beast of the financial district",
    points: 100,
  },
  {
    id: "STFE",
    name: "Staten Island Ferry",
    zone: "Downtown",
    lat: 40.7016,
    lng: -74.0134,
    secret: "STFE_BOAT_6W9M_SECRET",
    hint: "Free ride to Liberty",
    points: 125,
  },
  {
    id: "WTSQ",
    name: "Washington Square Park",
    zone: "Greenwich Village",
    lat: 40.7308,
    lng: -73.9973,
    secret: "WTSQ_ARCH_3Q7P_SECRET",
    hint: "The arch that mirrors Paris",
    points: 100,
  },
  {
    id: "CHTN",
    name: "Chinatown Gate",
    zone: "Chinatown",
    lat: 40.7155,
    lng: -73.9977,
    secret: "CHTN_GATE_8K4L_SECRET",
    hint: "Dragons guard the entrance",
    points: 100,
  },
  {
    id: "SOHO",
    name: "SoHo Cast Iron",
    zone: "SoHo",
    lat: 40.7233,
    lng: -74.0030,
    secret: "SOHO_IRON_5R2W_SECRET",
    hint: "Historic architecture in iron",
    points: 125,
  },
  {
    id: "CHEL",
    name: "Chelsea Market",
    zone: "Chelsea",
    lat: 40.7425,
    lng: -74.0059,
    secret: "CHEL_FOOD_7N9Q_SECRET",
    hint: "Where Oreos were born",
    points: 100,
  },
  {
    id: "DUMB",
    name: "DUMBO Waterfront",
    zone: "Brooklyn",
    lat: 40.7033,
    lng: -73.9888,
    secret: "DUMB_VIEW_4M8K_SECRET",
    hint: "Manhattan framed by bridges",
    points: 150,
  },
  {
    id: "PROS",
    name: "Prospect Park",
    zone: "Brooklyn",
    lat: 40.6602,
    lng: -73.9690,
    secret: "PROS_PARK_9P3L_SECRET",
    hint: "Brooklyn's green heart",
    points: 150,
  },
];

const LANDMARKS_PUBLIC = LANDMARKS.map(({ secret, ...rest }) => rest);

// Zone definitions with bonuses
const ZONES = {
  "Midtown": { bonus: 0, color: "#00f5d4" },
  "Downtown": { bonus: 10, color: "#9b5de5" },
  "Uptown": { bonus: 10, color: "#fee440" },
  "Chelsea": { bonus: 15, color: "#ff4d6d" },
  "Brooklyn": { bonus: 20, color: "#06ffa5" },
  "Greenwich Village": { bonus: 15, color: "#f15bb5" },
  "Chinatown": { bonus: 15, color: "#ffbe0b" },
  "SoHo": { bonus: 15, color: "#00bbf9" },
};

module.exports = { LANDMARKS, LANDMARKS_PUBLIC, ZONES };